# Generated by Django 4.2.6 on 2023-10-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='App_Formulario')),
                ('password_1', models.CharField(max_length=50)),
                ('password_2', models.CharField(max_length=50)),
                ('suscrito', models.BooleanField(default=False)),
            ],
        ),
    ]
