# Generated by Django 4.2.6 on 2023-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Plantilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('adulto', models.BooleanField(verbose_name='mayor de edad')),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nacimiento',
            field=models.DateField(verbose_name='fecha de nacimiento'),
        ),
    ]
